# Generated by Django 3.2.8 on 2021-10-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinreview',
            name='text',
            field=models.CharField(default='No comments...', max_length=500),
        ),
    ]
